version: '3.8'

services:
  warehouse-app:
    build: .
    container_name: warehouse-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=warehouse
      - SPRING_DATASOURCE_URL=jdbc:postgresql://warehouse-db:5432/warehouse_db
      - SPRING_DATASOURCE_USERNAME=my_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      warehouse-db:
        condition: service_healthy

  warehouse-db:
    image: postgres:13
    container_name: warehouse-db
    environment:
      - POSTGRES_DB=warehouse_db
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=password
    volumes:
      - warehouse_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user -d warehouse_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  warehouse_postgres_data: